name: move_to_earn
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

// version: 1.1.4+59
#ios version

#android version
version: 1.1.7+73

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lambda:
    path: ./lambda
  pedometer_db:
    path: ./pedometer_db

  pedometer: ^4.0.1
  fl_chart: ^0.68.0
  smooth_page_indicator: ^1.1.0
  get: ^4.6.6
  url_launcher: ^6.2.2
  flutter_svg: ^2.0.10+1
  skeletons: ^0.0.3
  lottie: ^3.1.0
  flutter_screenutil: ^5.9.0
  local_auth: ^2.1.6
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  curved_navigation_bar: ^1.0.3
  molten_navigationbar_flutter: ^1.0.1
  # share_plus: ^7.0.1
  # GOOGLE MAP
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  firebase_dynamic_links: ^5.3.3
  permission_handler: ^11.3.1
  iconsax: ^0.0.8
  pinput: ^4.0.0
  flutter_html: ^3.0.0-beta.2
  image_picker: ^1.0.5
  flutter_exif_rotation: ^0.5.1
  flutter_localization: ^0.2.0
  cached_network_image: ^3.3.1
  qr_flutter: ^4.1.0
  hive: ^2.2.3
  intl: ^0.18.1
  flutter_spinkit: ^5.2.0
  flutter_share: ^2.0.0
  clipboard: ^0.1.3
  percent_indicator: ^4.2.3
  package_info_plus: ^8.0.0
  firebase_remote_config: ^4.2.4
  firebase_analytics: ^10.4.4
  cron: ^0.6.0
  cloud_firestore: ^4.9.0
  firebase_ui_firestore: ^1.5.6
  shared_preferences: ^2.2.0
  android_alarm_manager_plus: ^4.0.1
  wakelock_plus: ^1.1.1
  connectivity_plus: ^5.0.2
  blur: ^3.1.0
  flutter_pin_code_fields: ^2.2.0
  google_mobile_ads: ^5.0.0
  dio: ^5.4.0
  location: ^6.0.1
  gradient_borders: ^1.0.0
  firebase_crashlytics: ^3.4.18
  loading_animation_widget: ^1.2.1
  carousel_slider: ^4.2.1
  nb_utils: ^6.1.3
  health: ^10.2.0
  buttons_tabbar: ^1.3.8
  loadmore: ^2.1.0
  stylish_bottom_bar: ^1.1.0
  google_nav_bar: ^5.0.6
  flutter_background_service_android: ^6.2.2
  flutter_local_notifications: ^17.0.0
  flutter_background_service: ^5.0.5
  mdi: ^5.0.0-nullsafety.0
  flutter_svg_provider: ^1.0.7
  action_slider: ^0.7.0
  rotated_corner_decoration: ^2.1.0+1
  tab_container: ^3.5.3
  #pedometer_db: ^0.1.1
  health_kit_reporter: ^2.1.1
  flutter_slidable: ^3.1.0
  flutter_toggle_tab: ^1.4.1
  device_info_plus: ^10.1.0
  app_settings: ^5.1.1
  dropdown_button2: ^2.3.9
  apple_product_name: ^3.1.0
  flutter_calendar_carousel: ^2.4.3
  quiver: ^3.2.1
  custom_pop_up_menu: ^1.2.4
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/invite/
    - assets/images/splash_images/
    - assets/images/onboarding_images/
    - assets/images/welcome_images/
    - assets/images/login_images/
    - assets/images/signup_images/
    - assets/images/coupon_images/
    - assets/images/challenge_images/
    - assets/icon-svg/icon/
    - assets/icon-svg/
    - assets/icon-png/
    - assets/images/home_images/
    - assets/images/home_images/vectors/
    - assets/images/profile_images/
    - assets/suvdaa/care_button.svg
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
        - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito/Nunito-MediumItalic.ttf
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
